### ISSUE TITLE
Showing patreons on the map really necessary ?

### ISSUE THREAD

**Issue by zanco** [projecthorus/sondehub-tracker#100]
Sorry for a bit offtopic non technical issue, but am I the only one to find the different receiver colors showing who did not support the sondehub tracker page not the right way ?

A page with thank you to the sponsors instead of "blaming the wrong coloured receivers (which this is in my opinion)"  could be a good idea.

Just my 2 Eurocents...

Ben - PE2BZ from the Netherlands

**Comment by darksidelemm** [comment]
"Blaming the wrong coloured receivers" is certainly not what we were going for. The intent was to *thank* those that did donate. 
The problem is that doing this programatically (which means less work required to maintain any said lists - remember there are 400+ stations on the map!) is not easy - Patreon supplies an API which helps with this, Paypal does not. With Patreon it's an obvious binary state - someone is supporting the tracker at a given time, or they are not. 
Doing this with a once-off Paypal donation gets more difficult - do you set the same break-points as with Patreon? When do you change the state of an icon? This would all have to be done manually. I don't have an easy solution to this.
