### ISSUE TITLE
Invalid Vehicle Coordinates?

### ISSUE THREAD

**Issue by ZigiWalter** [projecthorus/sondehub-tracker#140]
Hi,

Strangely, queries like "https://api.v2.sondehub.org/predictions?vehicles=" started returning unexpected "latitude" values - smaller than -90.0:

`{"vehicle": "T2341087", "time": "2021-09-13T19:46:05Z", "latitude": -113.65255007520318, "longitude": 32.88091998081654, "altitude": 19084.63, ...}`

Shouldn't it be limited to [-90, 90]...?

Thanks.

**Comment by darksidelemm** [comment]
This is not a tracker issue, but a sondehub-infra issue, probably related to the recent predictor changes.

The values in the prediction path array thats included in that response should be valid.

**Comment by TheSkorm** [comment]
Yup, this is a bug introduced in the predictor. I've just rolled out a fix. The root cause is ElasticSearch refers to these values inconsistently and as that data isn't used on the tracker I never noticed.
<img width="791" alt="image" src="https://user-images.githubusercontent.com/234867/133176292-a1e7b7d8-39d3-4bf3-9611-ddbd3f3c319e.png">
