### ISSUE TITLE
Open webpage centered at location

### ISSUE THREAD

**Issue by markdconner** [projecthorus/sondehub-tracker#270]
When using Sondehub on Android, the webpage centers on the location provided by the phone.  However, when I open it on my Win10 laptop (using the webapp or on sondehub.org inside of Chrome), the proper lat/lon shows in the upper left but the page is actually centered about 50N 0E.  For me and perhaps others, this wastes several database requests over Europe before I can recenter the page over my location in the central US.  Can this be modified to open over the user location?
![image](https://user-images.githubusercontent.com/49458752/200204992-ac75cfc6-d37a-4a97-8889-3521d908528e.png)

**Comment by darksidelemm** [comment]
The page can only get your location after it loads.

The best way to handle this problem is to pan to where you are interested in, then copy that URL, which will have the view coordinates in it.

As for 'wasting database requests' - you get all the data, regardless of location. It doesn't matter where you are panned to when the page loads,.

**Comment by markdconner** [comment]
Thanks for the info.  I was thinking the database request mechanism knew about the view domain.
