### ISSUE TITLE
Sonde tracked from recovery spot to home

### ISSUE THREAD

**Issue by swilson317** [projecthorus/sondehub-tracker#288]
Hi there, I recovered V0921235. Oddly...I checked it before I left the area and it was not flashing. But then a friend mentioned that there is a path from the recovery location to my house. I'm not sure why. But I would think that once a radiosonde is recovered, it shouldn't be tracked anymore.

Is is possible for someone to erase the track from the recovery location to my house in Fremont?

Thanks, Steve

**Comment by darksidelemm** [comment]
RS41s do not flash their LEDs once launched, this is expected behaviour. 
It would have still been transmitting once picked up, and if there was a receiver in range (perhaps your own?) then it will be received and uploaded to SondeHub. You need to turn them off by holding down the power button, then verifying power-off with a local receiver.

As a rule, we don't delete data from the SondeHub database.
