### ISSUE TITLE
Grafana receiver reported frequency  could use a filter

### ISSUE THREAD

**Issue by zanco** [projecthorus/sondehub-tracker#324]
Hi, 
![image](https://github.com/projecthorus/sondehub-tracker/assets/4477734/b59331d7-ab1e-42fc-9a47-24524bf7e404)

Having most RS41's over here in the EU running 4fsk on 2 different frequencies at the same time it would be an improvement if the reported frequencies where each filtered by some "common sense" , like, if distance between reports is larger as xx kHz assume it's a different transmitter frequency ?

Thanks,
Ben

**Comment by darksidelemm** [comment]
This won't be resolved by filtering, but it might be resolved by using scatter plot instead of a line plot:
<img width="746" alt="Screen Shot 2024-06-21 at 07 54 48" src="https://github.com/projecthorus/sondehub-tracker/assets/1040275/a380395f-ef95-4340-a89a-16389293e34d">

I think this is probably the best we can do.

**Comment by zanco** [comment]
That looks way better ! Thanks for this solution
